OnlineStore_Ecommerce/Areas/Admin/Controllers/ProductTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineStore_Ecommerce.Data;
using OnlineStore_Ecommerce.Models;

namespace OnlineStore_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ProductTypesController : Controller
    {
        private readonly ApplicationDbContext context;

        public ProductTypesController(ApplicationDbContext context)
        {
            this.context = context;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(context.ProductTypes.ToList());
        }

        //Create GET Action method
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //Create Post Action method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductTypes model)
        {
            if (ModelState.IsValid)
            {
                context.ProductTypes.Add(model);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        //Edit GET Action method
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return NotFound();
            var productType = context.ProductTypes.Find(id);
            if (productType == null)
                return NotFound();
            return View(productType);
        }

        //Edit Post Action method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductTypes model)
        {
            if (ModelState.IsValid)
            {
                var productType = context.ProductTypes.Find(model.Id);
                if (productType != null)
                    productType.ProductType = model.ProductType;
                else
                    return View(productType);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        //Details GET Action method
        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();
            var productType = context.ProductTypes.Find(id);
            if (productType == null)
                return NotFound();
            return View(productType);
        }

        //Details Post Action method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ProductTypes model)
        {
            return RedirectToAction(nameof(Index));
        }

        //Delete GET Action method
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();
            var productType = context.ProductTypes.Find(id);
            if (productType == null)
                return NotFound();
            context.ProductTypes.Remove(productType);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineStore_Ecommerce/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineStore_Ecommerce.Data;
using OnlineStore_Ecommerce.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace OnlineStore_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IHostingEnvironment hostingEnvironment;
        public ProductsController(ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            this.context = context;
            this.hostingEnvironment = hostingEnvironment;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View(context.Products.Include(P=>P.ProductType).Include(S=>S.SpecialTag).ToList());
        }
        [HttpPost]
        public IActionResult Index(decimal? lowAmount,decimal? largeAmount)
        {
            if(lowAmount == null || largeAmount == null)
            {
                return View(context.Products.Include(P=>P.ProductType).Include(S => S.SpecialTag).ToList());
            }
            return View(context.Products.Include(P => P.ProductType).Include(S => S.SpecialTag)
                .Where(c=>c.Price>=lowAmount && c.Price<=largeAmount).ToList());
        }

        //Create GET Action method
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["productTypeId"] = new SelectList(context.ProductTypes.ToList(),"Id","ProductType");
            ViewData["TagsId"] = new SelectList(context.SpecialTags.ToList(), "Id", "Name");
            return View();
        }

        //Create Post Action method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Products model,IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if(image != null)
                {
                    var path = Path.Combine(hostingEnvironment.WebRootPath + "\\Images\\" + Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(path,FileMode.Create));
                    model.Image = "Images\\" +  image.FileName;
                }
                context.Products.Add(model);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .Select(x => new { x.Key, x.Value.Errors })
            .ToArray();
            ViewData["productTypeId"] = new SelectList(context.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagsId"] = new SelectList(context.SpecialTags.ToList(), "Id", "Name");
            return View(model);
        }

        //Edit GET Action method
        [HttpGet]
        public IActionResult Edit(int ?id)
        {
            if(id == null)
                return NotFound();
            //var model = context.Products.Find(id);
            var model = context.Products.Include(P => P.ProductType).Include(S => S.SpecialTag).FirstOrDefault(c => c.Id == id);
            if (model == null)
                return NotFound();
            ViewData["productTypeId"] = new SelectList(context.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagsId"] = new SelectList(context.SpecialTags.ToList(), "Id", "Name");
            return View(model);
        }
        //EDit Post Action method
        [HttpPost]
        public async Task<IActionResult> Edit(Products model, IFormFile? image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var path = Path.Combine(hostingEnvironment.WebRootPath + "\\Images\\" + Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(path, FileMode.Create));
                    model.Image = "Images\\" + image.FileName;
                }
                var products = context.Products.Find(model.Id);

                products.Name = model.Name;
                products.Price = model.Price;
                products.Image = model.Image;
                products.IsAvailable = model.IsAvailable;
                products.ProductColor = model.ProductColor;
                products.ProductType = model.ProductType;
                products.ProductTypeId = model.ProductTypeId;
                products.SpecialTag = model.SpecialTag;
                products.SpecialTagId = model.SpecialTagId;

                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .Select(x => new { x.Key, x.Value.Errors })
            .ToArray();
            ViewData["productTypeId"] = new SelectList(context.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagsId"] = new SelectList(context.SpecialTags.ToList(), "Id", "Name");
            return View(model);
        }
        //Details GET Action method
        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();
            var model = context.Products.Include(P => P.ProductType).Include(S => S.SpecialTag).FirstOrDefault(c => c.Id == id);
            if (model == null)
                return NotFound();
            ViewData["productTypeId"] = new SelectList(context.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagsId"] = new SelectList(context.SpecialTags.ToList(), "Id", "Name");
            return View(model);
        }
        //Details Post Action method
        [HttpPost]
        public IActionResult Details(ProductTypes model)
        {
            return RedirectToAction(nameof(Index));
        }
        //Delete
        public IActionResult Delete(int? id)
        {
            var products = context.Products.Find(id);
            if(products != null)
            {
                context.Products.Remove(products);
                context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineStore_Ecommerce/Areas/Admin/Controllers/SpecialTagsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore_Ecommerce.Data;
using OnlineStore_Ecommerce.Models;

namespace OnlineStore_Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialTagsController : Controller
    {
        private readonly ApplicationDbContext context;

        public SpecialTagsController(ApplicationDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            return View(context.SpecialTags.ToList());
        }

        //Create GET Action method
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //Create Post Action method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SpecialTags model)
        {
            if (ModelState.IsValid)
            {
                context.SpecialTags.Add(model);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        //Edit GET Action method
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return NotFound();
            var SpecialTag = context.SpecialTags.Find(id);
            if (SpecialTag == null)
                return NotFound();
            return View(SpecialTag);
        }

        //Edit Post Action method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SpecialTags model)
        {
            if (ModelState.IsValid)
            {
                var SpecialTag = context.SpecialTags.Find(model.Id);
                if (SpecialTag != null)
                    SpecialTag.Name = model.Name;
                else
                    return View(SpecialTag);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        //Details GET Action method
        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();
            var SpecialTag = context.SpecialTags.Find(id);
            if (SpecialTag == null)
                return NotFound();
            return View(SpecialTag);
        }

        //Details Post Action method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(SpecialTags model)
        {
            return RedirectToAction(nameof(Index));
        }

        //Delete GET Action method
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();
            var SpecialTag = context.SpecialTags.Find(id);
            if (SpecialTag == null)
                return NotFound();
            context.SpecialTags.Remove(SpecialTag);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineStore_Ecommerce/Views/Shared/ButtonPartial.cshtml
@model int
<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model">Edit</a>
        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model">Delete</a>
        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model">Details</a>
    </div>
</td>

OnlineStore_Ecommerce/Views/Shared/_Layout.cshtml
@using System.Net.Http;
@using OnlineStore_Ecommerce.Utility;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("rolename");
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products == null)
        products = new List<Products>();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStore_Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
@*    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />*@    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineStore_Ecommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineStore_Ecommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(userRole == "Super User")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Tags</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">Cart(@products.Count())</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnlineStore_Ecommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
@*    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
*@    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlineStore_Ecommerce/Views/Shared/_PartialView.cshtml
@model string
<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model">Edit</a>
        <a asp-action="Locout" class="btn btn-danger" asp-route-id="@Model">Locout</a>
        <a asp-action="Detatils" class="btn btn-success" asp-route-id="@Model">Details</a>
    </div>
</td>